# Kafka servers. Best not to have only one
bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094

# This should really be a parameter!^
# bootstrap-servers: xx.xx.xx.xx:9092,xx.xx.xx.xx:9093,xx.xx.xx.xx:9094

# Leave 8080 for Hazelcast Management Center
server.port: 0

spring:
  main:
    banner-mode: 'off'
    
