---
# =========================================================
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pod-hazelcast-client
spec:
  replicas: 1
  serviceName: service-hazelcast-server
  selector:
    matchLabels:
      app: pod-hazelcast-client
  template:
    metadata:
      labels:
        app: pod-hazelcast-client
    spec:
      containers:
        - env:
          - name: K8S
            value: "true"
          image: "zappa/hazelcast-client"
          imagePullPolicy: Never
          # Regularly ok
          livenessProbe:
            httpGet:
              path: /k8s
              port: 8080
          name: container-hazelcast-client
          # Initially ok
          readinessProbe:
            httpGet:
              path: /k8s
              port: 8080
            initialDelaySeconds: 30
---
# =========================================================
---
apiVersion: v1
kind: Service
metadata:
  name: service-hazelcast-client
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: pod-hazelcast-client
  type: LoadBalancer
---
