# =========================================================
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pod-hazelcast-server
spec:
  replicas: 1
  serviceName: service-hazelcast-server
  selector:
    matchLabels:
      app: pod-hazelcast-server
  template:
    metadata:
      labels:
        app: pod-hazelcast-server
    spec:
      containers:
        - env:
          - name: K8S
            value: "true"
          image: "zappa/hazelcast-server"
          imagePullPolicy: Never
          # Regularly ok
          livenessProbe:
            httpGet:
              path: /k8s
              port: 8080
          name: container-hazelcast-server
          # Initially ok
          readinessProbe:
            httpGet:
              path: /k8s
              port: 8080
            initialDelaySeconds: 30
---
# =========================================================
---
apiVersion: v1
kind: Service
metadata:
  name: service-hazelcast-server
spec:
  clusterIP: None
  selector:
    app: pod-hazelcast-server
  ports:
  - protocol: TCP
    port: 5701
    targetPort: 5701
---
---
